'use client';
import { useState } from 'react';
import { formatDate, text } from '@/lib/model';
import { mutate, MutationError } from '@/lib/client';
import type { PageData, Row } from '@/lib/types';
import { Modal } from './Modal';
export function Tokens({data}:{data:PageData}) {
  const [issued,setIssued]=useState<Row|null>(null);const [nonce,setNonce]=useState(data.issueNonce||'');
  const [tokens,setTokens]=useState(data.tokens||[]);
  const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');const [error,setError]=useState('');
  const [revoke,setRevoke]=useState<Row|null>(null);
  const submit=async(form:FormData)=>{setBusy(true);setError('');try{const result=await mutate(form);setIssued(result.issuedToken||null);setNonce(result.issueNonce);setTokens(result.tokens||[]);setMessage(result.message);setRevoke(null);}catch(e){if(e instanceof MutationError&&typeof e.payload.issueNonce==='string')setNonce(e.payload.issueNonce);setError(e instanceof Error?e.message:'Не удалось выполнить действие.');}finally{setBusy(false);}};
  return <section><header className="page-head"><div><span className="eyebrow">Доступ к API</span><h1>API-токены</h1><p>Отдельные права и сроки действия для каждого сервиса.</p></div><span className={'badge '+(data.tokenConfigured?'good':'bad')}>{data.tokenConfigured?'Подключено':'Не настроено'}</span></header>
    {(error||data.tokenError)&&<p className="notice bad" role="alert">{error||data.tokenError}</p>}{message&&<p className="notice" role="status">{message}</p>}
    {issued&&<section className="secret-card" role="status"><span className="eyebrow">Показывается один раз</span><h2>Скопируйте новый токен</h2><p>После ухода со страницы секрет восстановить нельзя.</p><code>{text(issued.token)}</code><button type="button" className="button" onClick={async()=>{try{await navigator.clipboard.writeText(text(issued.token));setMessage('Токен скопирован.');}catch{setError('Выделите и скопируйте токен вручную.');}}}>Скопировать</button></section>}
    <div className="token-layout"><form className="panel-card" onSubmit={e=>{e.preventDefault();void submit(new FormData(e.currentTarget));}}><h2>Выпустить токен</h2><input type="hidden" name="action" value="issue_api_token"/><input type="hidden" name="csrf" value={data.csrf}/><input type="hidden" name="form_nonce" value={nonce}/>
      <label><span>Название сервиса</span><input name="name" placeholder="Например, сайт с колодами" required maxLength={120}/></label><label><span>Срок действия, дней</span><input name="expires_in_days" type="number" min={1} max={365} defaultValue={90} required/></label><fieldset><legend>Права доступа</legend>{Object.entries(data.scopeCatalog||{}).map(([key,name])=><label className="check-label" key={key}><input type="checkbox" name="scopes[]" value={key} defaultChecked={key==='database:read'}/>{name.label}<small>{name.description}</small></label>)}</fieldset><button type="submit" className="button" disabled={busy||!data.tokenConfigured}>{busy?'Выпускаем…':'Выпустить'}</button></form>
      <div className="table-scroll"><table><thead><tr><th>Название</th><th>Права</th><th>Действует до</th><th>Использование</th><th>Действия</th></tr></thead><tbody>{tokens.map(token=><tr key={text(token.id)}><td><strong>{text(token.name)}</strong><code>{text(token.id)}</code>{Boolean(token.revoked_at)&&<span className="badge bad">Отозван</span>}</td><td>{Array.isArray(token.scopes)?token.scopes.join(', '):text(token.scopes)}</td><td>{formatDate(token.expires_at)}</td><td>{text(token.requests_used??token.requests_count??token.usage_total,'0')}</td><td>{!Boolean(token.revoked_at)&&text(token.id)!==data.managerId&&<button type="button" className="link-button danger-text" onClick={()=>setRevoke(token)}>Отозвать</button>}</td></tr>)}</tbody></table>{!tokens.length&&<p className="empty">Токены отсутствуют.</p>}</div></div>
    {revoke&&<Modal title="Отозвать токен?" onClose={()=>setRevoke(null)}><p>Сервис «{text(revoke.name)}» потеряет доступ к API.</p><div className="form-actions"><button type="button" className="button secondary" onClick={()=>setRevoke(null)}>Отмена</button><button type="button" className="button danger" disabled={busy} onClick={()=>{const form=new FormData();form.set('action','revoke_api_token');form.set('csrf',data.csrf);form.set('token_id',text(revoke.id));void submit(form);}}>Отозвать</button></div></Modal>}
  </section>;
}
