server {
    listen 151.80.21.140:80;
    listen [2001:41d0:c:c8c::]:80;
    server_name db.kolodahs.ru;

    access_log /var/www/httpd-logs/db.kolodahs.ru.access.log;
    error_log /var/www/httpd-logs/db.kolodahs.ru.error.log notice;

    return 308 https://api.kolodahearthstone.com$request_uri;
}

server {
    listen 151.80.21.140:443 ssl;
    listen [2001:41d0:c:c8c::]:443 ssl;
    server_name db.kolodahs.ru;

    ssl_certificate "/etc/ssl/cloudflare-origin/db.kolodahs.ru.pem";
    ssl_certificate_key "/etc/ssl/cloudflare-origin/db.kolodahs.ru.key";
    ssl_ciphers EECDH:+AES256:-3DES:RSA+AES:!NULL:!RC4;
    ssl_prefer_server_ciphers on;
    ssl_protocols TLSv1.2 TLSv1.3;

    access_log /var/www/httpd-logs/db.kolodahs.ru.access.log;
    error_log /var/www/httpd-logs/db.kolodahs.ru.error.log notice;

    return 308 https://api.kolodahearthstone.com$request_uri;
}
