-- Схема базы карт Hearthstone: MySQL, БД `generator`.
--
-- Только структура. Данные наполняются парсерами из panel/scripts,
-- см. ARCHITECTURE.md. Разовые backup-таблицы вида *_backup_YYYYMMDD
-- в выгрузку не входят.
--
-- Таблиц: 36, представлений: 0.

SET NAMES utf8mb4;

-- ----------------------------------------------------------------------
CREATE TABLE `battlegrounds_card_changes` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `card_id` varchar(64) NOT NULL,
  `source` varchar(32) NOT NULL,
  `old_hash` char(64) DEFAULT NULL,
  `new_hash` char(64) DEFAULT NULL,
  `change_type` varchar(16) NOT NULL,
  `payload_json` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`payload_json`)),
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_card_created` (`card_id`,`created_at`),
  KEY `idx_source_created` (`source`,`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ----------------------------------------------------------------------
CREATE TABLE `battlegrounds_card_import_runs` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `source` varchar(32) NOT NULL,
  `started_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `finished_at` timestamp NULL DEFAULT NULL,
  `status` varchar(16) NOT NULL DEFAULT 'running',
  `scanned` int(10) unsigned NOT NULL DEFAULT 0,
  `inserted` int(10) unsigned NOT NULL DEFAULT 0,
  `updated` int(10) unsigned NOT NULL DEFAULT 0,
  `changed` int(10) unsigned NOT NULL DEFAULT 0,
  `error` text DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_source_started` (`source`,`started_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ----------------------------------------------------------------------
CREATE TABLE `battlegrounds_card_wiki_meta` (
  `card_id` varchar(64) NOT NULL,
  `dbf` int(10) unsigned DEFAULT NULL,
  `wiki_page_title` varchar(255) DEFAULT NULL,
  `wiki_page_url` varchar(512) DEFAULT NULL,
  `artist` varchar(255) DEFAULT NULL,
  `race` varchar(128) DEFAULT NULL,
  `minion_type` varchar(128) DEFAULT NULL,
  `wiki_mechanics_json` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`wiki_mechanics_json`)),
  `wiki_tags_json` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`wiki_tags_json`)),
  `availability_json` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`availability_json`)),
  `sounds_json` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`sounds_json`)),
  `external_links_json` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`external_links_json`)),
  `related_cards_json` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`related_cards_json`)),
  `related_card_ids_json` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`related_card_ids_json`)),
  `card_changes_json` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`card_changes_json`)),
  `source_payload_json` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`source_payload_json`)),
  `source_hash` char(64) DEFAULT NULL,
  `status` varchar(16) NOT NULL DEFAULT 'ok',
  `error` text DEFAULT NULL,
  `fetched_at` timestamp NULL DEFAULT NULL,
  `changed_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`card_id`),
  KEY `idx_dbf` (`dbf`),
  KEY `idx_status` (`status`),
  KEY `idx_changed_at` (`changed_at`),
  KEY `idx_fetched_at` (`fetched_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ----------------------------------------------------------------------
CREATE TABLE `battlegrounds_card_wiki_related` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `card_id` varchar(64) NOT NULL,
  `related_card_id` varchar(64) DEFAULT NULL,
  `heading` varchar(255) DEFAULT NULL,
  `title` varchar(255) DEFAULT NULL,
  `caption` varchar(255) DEFAULT NULL,
  `url` varchar(512) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_card_related` (`card_id`,`related_card_id`,`heading`,`title`),
  KEY `idx_card_id` (`card_id`),
  KEY `idx_related_card_id` (`related_card_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ----------------------------------------------------------------------
CREATE TABLE `battlegrounds_cards` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(160) NOT NULL,
  `name_en` varchar(160) DEFAULT NULL,
  `card_id` varchar(64) NOT NULL,
  `dbf` int(10) unsigned DEFAULT NULL,
  `card_type` varchar(16) NOT NULL DEFAULT 'minion',
  `variant_kind` varchar(16) NOT NULL DEFAULT 'base',
  `base_dbf` int(10) unsigned DEFAULT NULL,
  `base_card_id` varchar(64) DEFAULT NULL,
  `premium_dbf` int(10) unsigned DEFAULT NULL,
  `tavern_tier` tinyint(3) unsigned DEFAULT NULL,
  `creature_type` varchar(32) DEFAULT NULL,
  `attack` smallint(6) DEFAULT NULL,
  `health` smallint(6) DEFAULT NULL,
  `in_pool` tinyint(1) NOT NULL DEFAULT 1,
  `duos_only` tinyint(1) NOT NULL DEFAULT 0,
  `card_image` varchar(255) DEFAULT NULL,
  `golden_image` varchar(255) DEFAULT NULL,
  `art_image` varchar(255) DEFAULT NULL,
  `framed_image` varchar(255) DEFAULT NULL,
  `notes` text DEFAULT NULL,
  `source` varchar(32) DEFAULT NULL,
  `source_hash` char(64) DEFAULT NULL,
  `first_seen_at` timestamp NULL DEFAULT NULL,
  `last_seen_at` timestamp NULL DEFAULT NULL,
  `changed_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_battlegrounds_cards_card_id` (`card_id`),
  KEY `idx_battlegrounds_cards_dbf` (`dbf`),
  KEY `idx_battlegrounds_cards_tavern_tier` (`tavern_tier`),
  KEY `idx_battlegrounds_cards_creature_type` (`creature_type`),
  KEY `idx_in_pool` (`in_pool`),
  KEY `idx_duos_only` (`duos_only`),
  KEY `idx_bg_filters` (`in_pool`,`duos_only`,`tavern_tier`,`creature_type`),
  KEY `idx_name_en` (`name_en`),
  KEY `idx_card_type` (`card_type`),
  KEY `idx_source_hash` (`source_hash`),
  KEY `idx_last_seen_at` (`last_seen_at`),
  KEY `idx_bg_variant_kind` (`variant_kind`),
  KEY `idx_bg_base_dbf` (`base_dbf`),
  KEY `idx_bg_base_card_id` (`base_card_id`),
  KEY `idx_bg_premium_dbf` (`premium_dbf`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ----------------------------------------------------------------------
CREATE TABLE `battlegrounds_hero_gallery` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `hero_card_id` varchar(64) NOT NULL,
  `caption` varchar(255) DEFAULT NULL,
  `file_title` varchar(255) DEFAULT NULL,
  `file_url` varchar(512) DEFAULT NULL,
  `thumb_url` varchar(512) DEFAULT NULL,
  `file_page_url` varchar(512) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_hero_card_id` (`hero_card_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ----------------------------------------------------------------------
CREATE TABLE `battlegrounds_hero_powers` (
  `card_id` varchar(64) NOT NULL,
  `dbf` int(10) unsigned NOT NULL,
  `hero_dbf` int(10) unsigned DEFAULT NULL,
  `name` varchar(160) NOT NULL,
  `text` text DEFAULT NULL,
  `image` varchar(512) DEFAULT NULL,
  `crop_image` varchar(512) DEFAULT NULL,
  `locale` varchar(16) NOT NULL DEFAULT 'ru_RU',
  `source` varchar(32) NOT NULL DEFAULT 'blizzard',
  `source_payload_json` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`source_payload_json`)),
  `source_hash` char(64) DEFAULT NULL,
  `fetched_at` timestamp NULL DEFAULT NULL,
  `changed_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`card_id`),
  UNIQUE KEY `uniq_dbf_locale` (`dbf`,`locale`),
  KEY `idx_hero_dbf` (`hero_dbf`),
  KEY `idx_changed_at` (`changed_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ----------------------------------------------------------------------
CREATE TABLE `battlegrounds_hero_related` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `hero_card_id` varchar(64) NOT NULL,
  `related_card_id` varchar(64) DEFAULT NULL,
  `heading` varchar(255) DEFAULT NULL,
  `title` varchar(255) DEFAULT NULL,
  `caption` varchar(255) DEFAULT NULL,
  `url` varchar(512) DEFAULT NULL,
  `image_url` varchar(512) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_hero_card_id` (`hero_card_id`),
  KEY `idx_related_card_id` (`related_card_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ----------------------------------------------------------------------
CREATE TABLE `battlegrounds_hero_skins` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `hero_card_id` varchar(64) NOT NULL,
  `skin_card_id` varchar(64) DEFAULT NULL,
  `title` varchar(255) DEFAULT NULL,
  `url` varchar(512) DEFAULT NULL,
  `image_url` varchar(512) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_hero_card_id` (`hero_card_id`),
  KEY `idx_skin_card_id` (`skin_card_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ----------------------------------------------------------------------
CREATE TABLE `battlegrounds_heroes` (
  `card_id` varchar(64) NOT NULL,
  `dbf` int(10) unsigned NOT NULL,
  `hero_id` int(10) unsigned DEFAULT NULL,
  `name_en` varchar(160) NOT NULL,
  `name_ru` varchar(160) DEFAULT NULL,
  `health` smallint(6) DEFAULT NULL,
  `armor` smallint(6) DEFAULT NULL,
  `duos_armor` smallint(6) DEFAULT NULL,
  `armor_text` varchar(64) DEFAULT NULL,
  `artist` varchar(255) DEFAULT NULL,
  `race` varchar(128) DEFAULT NULL,
  `character_name` varchar(160) DEFAULT NULL,
  `as_hero` text DEFAULT NULL,
  `hero_description` text DEFAULT NULL,
  `hero_image_url` varchar(512) DEFAULT NULL,
  `hero_full_art_url` varchar(512) DEFAULT NULL,
  `wiki_page_title` varchar(255) DEFAULT NULL,
  `wiki_page_url` varchar(512) DEFAULT NULL,
  `hero_power_dbf` int(10) unsigned DEFAULT NULL,
  `hero_power_json` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`hero_power_json`)),
  `buddy_dbf` int(10) unsigned DEFAULT NULL,
  `buddy_json` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`buddy_json`)),
  `availability_json` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`availability_json`)),
  `hero_skins_json` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`hero_skins_json`)),
  `gallery_json` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`gallery_json`)),
  `card_changes_json` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`card_changes_json`)),
  `external_links_json` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`external_links_json`)),
  `source_payload_json` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`source_payload_json`)),
  `source_hash` char(64) DEFAULT NULL,
  `status` varchar(16) NOT NULL DEFAULT 'ok',
  `error` text DEFAULT NULL,
  `fetched_at` timestamp NULL DEFAULT NULL,
  `changed_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`card_id`),
  UNIQUE KEY `uniq_dbf` (`dbf`),
  KEY `idx_hero_id` (`hero_id`),
  KEY `idx_hero_power_dbf` (`hero_power_dbf`),
  KEY `idx_buddy_dbf` (`buddy_dbf`),
  KEY `idx_status` (`status`),
  KEY `idx_changed_at` (`changed_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ----------------------------------------------------------------------
CREATE TABLE `battlegrounds_library_cards` (
  `library` varchar(32) NOT NULL,
  `card_id` varchar(64) NOT NULL,
  `dbf` int(10) unsigned DEFAULT NULL,
  `name_ru` varchar(180) NOT NULL,
  `name_en` varchar(180) DEFAULT NULL,
  `text_ru` text DEFAULT NULL,
  `text_en` text DEFAULT NULL,
  `image_url` varchar(512) DEFAULT NULL,
  `image_gold_url` varchar(512) DEFAULT NULL,
  `crop_image_url` varchar(512) DEFAULT NULL,
  `full_art_source` varchar(32) DEFAULT NULL,
  `full_art_source_url` varchar(512) DEFAULT NULL,
  `local_full_art_url` varchar(512) DEFAULT NULL,
  `full_art_width` smallint(5) unsigned DEFAULT NULL,
  `full_art_height` smallint(5) unsigned DEFAULT NULL,
  `full_art_size` int(10) unsigned DEFAULT NULL,
  `full_art_sha1` char(40) DEFAULT NULL,
  `full_art_mime` varchar(64) DEFAULT NULL,
  `full_art_fetched_at` timestamp NULL DEFAULT NULL,
  `artist` varchar(255) DEFAULT NULL,
  `card_type` varchar(64) DEFAULT NULL,
  `card_type_id` smallint(5) unsigned DEFAULT NULL,
  `mana_cost` smallint(6) DEFAULT NULL,
  `in_pool` tinyint(1) NOT NULL DEFAULT 1,
  `pool_status` varchar(24) NOT NULL DEFAULT 'available',
  `group_slug` varchar(64) DEFAULT NULL,
  `group_name_ru` varchar(180) DEFAULT NULL,
  `tier_value` smallint(5) unsigned DEFAULT NULL,
  `tier_slug` varchar(64) DEFAULT NULL,
  `tier_name_ru` varchar(180) DEFAULT NULL,
  `sort_order` int(10) unsigned DEFAULT NULL,
  `wiki_page_title` varchar(255) DEFAULT NULL,
  `wiki_page_url` varchar(512) DEFAULT NULL,
  `source` varchar(64) NOT NULL,
  `source_payload_json` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`source_payload_json`)),
  `source_hash` char(64) DEFAULT NULL,
  `fetched_at` timestamp NULL DEFAULT NULL,
  `changed_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`library`,`card_id`),
  KEY `idx_library_pool` (`library`,`in_pool`),
  KEY `idx_library_status` (`library`,`pool_status`),
  KEY `idx_dbf` (`dbf`),
  KEY `idx_changed_at` (`changed_at`),
  KEY `idx_library_group` (`library`,`group_slug`),
  KEY `idx_library_tier` (`library`,`tier_value`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ----------------------------------------------------------------------
CREATE TABLE `battlegrounds_timewarped_cards` (
  `card_id` varchar(64) NOT NULL,
  `dbf` int(10) unsigned DEFAULT NULL,
  `name_en` varchar(180) NOT NULL,
  `name_ru` varchar(180) DEFAULT NULL,
  `text_en` text DEFAULT NULL,
  `text_ru` text DEFAULT NULL,
  `flavor` text DEFAULT NULL,
  `card_type` varchar(64) DEFAULT NULL,
  `card_type_id` smallint(5) unsigned DEFAULT NULL,
  `cost` smallint(6) DEFAULT NULL,
  `tavern_tier` tinyint(3) unsigned DEFAULT NULL,
  `attack` smallint(6) DEFAULT NULL,
  `health` smallint(6) DEFAULT NULL,
  `minion_type` varchar(128) DEFAULT NULL,
  `race` varchar(128) DEFAULT NULL,
  `artist` varchar(255) DEFAULT NULL,
  `card_image_url` varchar(512) DEFAULT NULL,
  `art_image_url` varchar(512) DEFAULT NULL,
  `golden_card_id` varchar(64) DEFAULT NULL,
  `golden_dbf` int(10) unsigned DEFAULT NULL,
  `golden_name_en` varchar(180) DEFAULT NULL,
  `golden_name_ru` varchar(180) DEFAULT NULL,
  `golden_text_en` text DEFAULT NULL,
  `golden_text_ru` text DEFAULT NULL,
  `golden_image_url` varchar(512) DEFAULT NULL,
  `wiki_page_title` varchar(255) DEFAULT NULL,
  `wiki_page_url` varchar(512) DEFAULT NULL,
  `wiki_mechanics_json` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`wiki_mechanics_json`)),
  `wiki_tags_json` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`wiki_tags_json`)),
  `availability_json` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`availability_json`)),
  `related_cards_json` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`related_cards_json`)),
  `related_card_ids_json` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`related_card_ids_json`)),
  `sounds_json` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`sounds_json`)),
  `gallery_json` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`gallery_json`)),
  `card_changes_json` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`card_changes_json`)),
  `external_links_json` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`external_links_json`)),
  `full_tags_json` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`full_tags_json`)),
  `source_payload_json` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`source_payload_json`)),
  `source_hash` char(64) DEFAULT NULL,
  `status` varchar(16) NOT NULL DEFAULT 'ok',
  `error` text DEFAULT NULL,
  `fetched_at` timestamp NULL DEFAULT NULL,
  `changed_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`card_id`),
  UNIQUE KEY `uniq_dbf` (`dbf`),
  KEY `idx_card_type` (`card_type`),
  KEY `idx_tavern_tier` (`tavern_tier`),
  KEY `idx_status` (`status`),
  KEY `idx_changed_at` (`changed_at`),
  KEY `idx_fetched_at` (`fetched_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ----------------------------------------------------------------------
CREATE TABLE `battlegrounds_timewarped_related` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `card_id` varchar(64) NOT NULL,
  `related_card_id` varchar(64) DEFAULT NULL,
  `heading` varchar(255) DEFAULT NULL,
  `title` varchar(255) DEFAULT NULL,
  `caption` varchar(255) DEFAULT NULL,
  `url` varchar(512) DEFAULT NULL,
  `image_url` varchar(512) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_card_id` (`card_id`),
  KEY `idx_related_card_id` (`related_card_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ----------------------------------------------------------------------
CREATE TABLE `battlegrounds_wiki_term_translations` (
  `term_type` varchar(32) NOT NULL,
  `term_en` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  `term_ru` varchar(255) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`term_type`,`term_en`),
  KEY `idx_term_type` (`term_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ----------------------------------------------------------------------
CREATE TABLE `cards` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `card_id` varchar(25) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `name` varchar(100) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `mana` varchar(5) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `attack` varchar(5) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `health` varchar(5) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `description` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `text` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `type` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `rarity` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `faction` varchar(100) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `collectible` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `howToGetGold` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `mechanics` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `set` varchar(100) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `race` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `playerClass` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `dbf` int(11) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `card_id` (`card_id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci;

-- ----------------------------------------------------------------------
CREATE TABLE `cards_de` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `card_id` varchar(25) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `name` varchar(100) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `mana` varchar(5) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `attack` varchar(5) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `health` varchar(5) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `description` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `text` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `type` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `rarity` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `faction` varchar(100) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `collectible` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `howToGetGold` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `mechanics` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `set` varchar(100) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `race` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `playerClass` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `card_id` (`card_id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci;

-- ----------------------------------------------------------------------
CREATE TABLE `cards_es` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `card_id` varchar(10) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `name` varchar(100) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `mana` varchar(5) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `attack` varchar(5) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `health` varchar(5) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `description` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `text` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `type` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `rarity` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `faction` varchar(100) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `collectible` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `howToGetGold` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `mechanics` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `set` varchar(100) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `race` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `playerClass` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `card_id` (`card_id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci;

-- ----------------------------------------------------------------------
CREATE TABLE `cards_fr` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `card_id` varchar(10) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `name` varchar(100) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `mana` varchar(5) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `attack` varchar(5) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `health` varchar(5) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `description` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `text` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `type` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `rarity` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `faction` varchar(100) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `collectible` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `howToGetGold` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `mechanics` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `set` varchar(100) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `race` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `playerClass` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `card_id` (`card_id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci;

-- ----------------------------------------------------------------------
CREATE TABLE `cards_pt` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `card_id` varchar(10) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `name` varchar(100) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `mana` varchar(5) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `attack` varchar(5) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `health` varchar(5) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `description` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `text` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `type` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `rarity` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `faction` varchar(100) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `collectible` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `howToGetGold` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `mechanics` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `set` varchar(100) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `race` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `playerClass` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `card_id` (`card_id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci;

-- ----------------------------------------------------------------------
CREATE TABLE `cards_ru` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `card_id` varchar(25) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `name` varchar(100) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `mana` varchar(5) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `attack` varchar(5) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `health` varchar(5) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `description` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `text` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `type` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `rarity` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `faction` varchar(100) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `collectible` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `howToGetGold` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `mechanics` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `set` varchar(100) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `race` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `playerClass` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `dbf` int(11) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `card_id` (`card_id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci;

-- ----------------------------------------------------------------------
CREATE TABLE `constructed_card_wiki_meta` (
  `card_id` varchar(64) NOT NULL,
  `dbf` int(10) unsigned DEFAULT NULL,
  `wiki_page_title` varchar(255) DEFAULT NULL,
  `wiki_page_url` varchar(512) DEFAULT NULL,
  `wiki_mechanics_json` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`wiki_mechanics_json`)),
  `wiki_tags_json` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`wiki_tags_json`)),
  `ban_lists_json` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`ban_lists_json`)),
  `gallery_json` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`gallery_json`)),
  `patch_changes_json` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`patch_changes_json`)),
  `external_links_json` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`external_links_json`)),
  `related_cards_json` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`related_cards_json`)),
  `related_card_ids_json` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`related_card_ids_json`)),
  `generated_card_pools_json` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`generated_card_pools_json`)),
  `generated_card_ids_json` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`generated_card_ids_json`)),
  `sounds_json` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`sounds_json`)),
  `golden_cards_json` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`golden_cards_json`)),
  `signature_cards_json` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`signature_cards_json`)),
  `diamond_cards_json` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`diamond_cards_json`)),
  `golden_animated_json` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`golden_animated_json`)),
  `signature_animated_json` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`signature_animated_json`)),
  `diamond_animated_json` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`diamond_animated_json`)),
  `source_payload_json` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`source_payload_json`)),
  `source_hash` char(64) DEFAULT NULL,
  `status` varchar(32) NOT NULL DEFAULT 'ok',
  `error` text DEFAULT NULL,
  `fetched_at` timestamp NULL DEFAULT NULL,
  `changed_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`card_id`),
  KEY `idx_constructed_wiki_dbf` (`dbf`),
  KEY `idx_constructed_wiki_status` (`status`),
  KEY `idx_constructed_wiki_changed_at` (`changed_at`),
  CONSTRAINT `fk_constructed_wiki_card` FOREIGN KEY (`card_id`) REFERENCES `constructed_cards` (`card_id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ----------------------------------------------------------------------
CREATE TABLE `constructed_cards` (
  `card_id` varchar(64) NOT NULL,
  `dbf` int(10) unsigned DEFAULT NULL,
  `slug` varchar(160) DEFAULT NULL,
  `collectible` tinyint(1) NOT NULL DEFAULT 0,
  `name_ru` varchar(255) DEFAULT NULL,
  `name_en` varchar(255) DEFAULT NULL,
  `text_ru` text DEFAULT NULL,
  `text_en` text DEFAULT NULL,
  `flavor_ru` text DEFAULT NULL,
  `flavor_en` text DEFAULT NULL,
  `card_set` varchar(80) DEFAULT NULL,
  `card_set_id` int(10) unsigned DEFAULT NULL,
  `card_type` varchar(80) DEFAULT NULL,
  `card_type_id` smallint(5) unsigned DEFAULT NULL,
  `rarity` varchar(80) DEFAULT NULL,
  `rarity_id` smallint(5) unsigned DEFAULT NULL,
  `class_slug` varchar(80) DEFAULT NULL,
  `class_id` smallint(5) unsigned DEFAULT NULL,
  `multi_class_json` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`multi_class_json`)),
  `minion_type` varchar(80) DEFAULT NULL,
  `minion_type_id` smallint(5) unsigned DEFAULT NULL,
  `spell_school` varchar(80) DEFAULT NULL,
  `spell_school_id` smallint(5) unsigned DEFAULT NULL,
  `mana_cost` smallint(6) DEFAULT NULL,
  `attack` smallint(6) DEFAULT NULL,
  `health` smallint(6) DEFAULT NULL,
  `durability` smallint(6) DEFAULT NULL,
  `armor` smallint(6) DEFAULT NULL,
  `artist` varchar(255) DEFAULT NULL,
  `image_url` varchar(512) DEFAULT NULL,
  `image_gold_url` varchar(512) DEFAULT NULL,
  `image_signature_url` varchar(512) DEFAULT NULL,
  `image_diamond_url` varchar(512) DEFAULT NULL,
  `animated_gold_url` varchar(512) DEFAULT NULL,
  `animated_signature_url` varchar(512) DEFAULT NULL,
  `animated_diamond_url` varchar(512) DEFAULT NULL,
  `crop_image_url` varchar(512) DEFAULT NULL,
  `local_image_url` varchar(512) DEFAULT NULL,
  `local_gold_image_url` varchar(512) DEFAULT NULL,
  `local_crop_image_url` varchar(512) DEFAULT NULL,
  `wiki_full_art_title` varchar(255) DEFAULT NULL,
  `wiki_full_art_url` varchar(512) DEFAULT NULL,
  `local_wiki_full_art_url` varchar(512) DEFAULT NULL,
  `wiki_full_art_file_page_url` varchar(512) DEFAULT NULL,
  `wiki_full_art_width` int(10) unsigned DEFAULT NULL,
  `wiki_full_art_height` int(10) unsigned DEFAULT NULL,
  `wiki_full_art_size` int(10) unsigned DEFAULT NULL,
  `wiki_full_art_sha1` char(40) DEFAULT NULL,
  `wiki_full_art_mime` varchar(80) DEFAULT NULL,
  `wiki_full_art_fetched_at` timestamp NULL DEFAULT NULL,
  `mechanics_json` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`mechanics_json`)),
  `referenced_tags_json` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`referenced_tags_json`)),
  `keyword_ids_json` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`keyword_ids_json`)),
  `wiki_page_title` varchar(255) DEFAULT NULL,
  `wiki_page_url` varchar(512) DEFAULT NULL,
  `source` varchar(64) NOT NULL DEFAULT 'pending',
  `source_payload_json` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`source_payload_json`)),
  `source_hash` char(64) DEFAULT NULL,
  `first_seen_at` timestamp NULL DEFAULT NULL,
  `last_seen_at` timestamp NULL DEFAULT NULL,
  `changed_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`card_id`),
  UNIQUE KEY `uniq_constructed_dbf` (`dbf`),
  KEY `idx_constructed_collectible` (`collectible`),
  KEY `idx_constructed_set` (`card_set`),
  KEY `idx_constructed_type` (`card_type`),
  KEY `idx_constructed_class` (`class_slug`),
  KEY `idx_constructed_rarity` (`rarity`),
  KEY `idx_constructed_changed_at` (`changed_at`),
  KEY `idx_constructed_updated_at` (`updated_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ----------------------------------------------------------------------
CREATE TABLE `constructed_diamond_cards` (
  `base_card_id` varchar(64) NOT NULL,
  `base_dbf` int(10) unsigned DEFAULT NULL,
  `diamond_card_id` varchar(80) NOT NULL,
  `diamond_dbf` int(10) unsigned DEFAULT NULL,
  `name_en` varchar(255) DEFAULT NULL,
  `name_ru` varchar(255) DEFAULT NULL,
  `card_set_id` int(10) unsigned DEFAULT NULL,
  `card_set` varchar(80) DEFAULT NULL,
  `card_type` varchar(80) DEFAULT NULL,
  `rarity` varchar(80) DEFAULT NULL,
  `class_slug` varchar(80) DEFAULT NULL,
  `mana_cost` smallint(6) DEFAULT NULL,
  `collectible` tinyint(1) NOT NULL DEFAULT 0,
  `section_slug` varchar(32) NOT NULL,
  `section_name_ru` varchar(80) NOT NULL,
  `in_standard` tinyint(1) NOT NULL DEFAULT 0,
  `in_wild` tinyint(1) NOT NULL DEFAULT 0,
  `image_url` varchar(512) DEFAULT NULL,
  `animated_url` varchar(512) DEFAULT NULL,
  `animated_source` varchar(64) DEFAULT NULL,
  `hearthpwn_url` varchar(512) DEFAULT NULL,
  `wiki_page_title` varchar(255) DEFAULT NULL,
  `wiki_page_url` varchar(512) DEFAULT NULL,
  `source` varchar(64) NOT NULL,
  `source_payload_json` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`source_payload_json`)),
  `source_hash` char(64) DEFAULT NULL,
  `fetched_at` timestamp NULL DEFAULT NULL,
  `changed_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`base_card_id`),
  KEY `idx_diamond_base_dbf` (`base_dbf`),
  KEY `idx_diamond_section` (`section_slug`),
  KEY `idx_diamond_standard` (`in_standard`),
  KEY `idx_diamond_wild` (`in_wild`),
  KEY `idx_diamond_changed_at` (`changed_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ----------------------------------------------------------------------
CREATE TABLE `constructed_format_cards` (
  `format_slug` varchar(32) NOT NULL,
  `card_id` varchar(64) NOT NULL,
  `dbf` int(10) unsigned DEFAULT NULL,
  `in_format` tinyint(1) NOT NULL DEFAULT 1,
  `availability_status` varchar(32) NOT NULL DEFAULT 'available',
  `rotation_year` smallint(5) unsigned DEFAULT NULL,
  `source` varchar(64) NOT NULL DEFAULT 'pending',
  `source_payload_json` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`source_payload_json`)),
  `source_hash` char(64) DEFAULT NULL,
  `first_seen_at` timestamp NULL DEFAULT NULL,
  `last_seen_at` timestamp NULL DEFAULT NULL,
  `changed_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`format_slug`,`card_id`),
  KEY `idx_constructed_format_dbf` (`format_slug`,`dbf`),
  KEY `idx_constructed_format_available` (`format_slug`,`in_format`,`availability_status`),
  KEY `idx_constructed_format_changed_at` (`changed_at`),
  KEY `fk_constructed_format_card` (`card_id`),
  CONSTRAINT `fk_constructed_format_card` FOREIGN KEY (`card_id`) REFERENCES `constructed_cards` (`card_id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ----------------------------------------------------------------------
CREATE TABLE `constructed_formats` (
  `format_slug` varchar(32) NOT NULL,
  `name_ru` varchar(80) NOT NULL,
  `name_en` varchar(80) NOT NULL,
  `description_ru` text DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`format_slug`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ----------------------------------------------------------------------
CREATE TABLE `constructed_import_runs` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `job` varchar(64) NOT NULL,
  `format_slug` varchar(32) DEFAULT NULL,
  `source` varchar(64) NOT NULL,
  `started_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `finished_at` timestamp NULL DEFAULT NULL,
  `status` varchar(32) NOT NULL DEFAULT 'running',
  `scanned` int(10) unsigned NOT NULL DEFAULT 0,
  `inserted` int(10) unsigned NOT NULL DEFAULT 0,
  `updated` int(10) unsigned NOT NULL DEFAULT 0,
  `changed` int(10) unsigned NOT NULL DEFAULT 0,
  `error` text DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_constructed_runs_job_started` (`job`,`started_at`),
  KEY `idx_constructed_runs_format_started` (`format_slug`,`started_at`),
  KEY `idx_constructed_runs_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ----------------------------------------------------------------------
CREATE ALGORITHM=UNDEFINED VIEW `constructed_standard_cards` AS select `c`.`card_id` AS `card_id`,`c`.`dbf` AS `dbf`,`c`.`slug` AS `slug`,`c`.`collectible` AS `collectible`,`c`.`name_ru` AS `name_ru`,`c`.`name_en` AS `name_en`,`c`.`text_ru` AS `text_ru`,`c`.`text_en` AS `text_en`,`c`.`flavor_ru` AS `flavor_ru`,`c`.`flavor_en` AS `flavor_en`,`c`.`card_set` AS `card_set`,`c`.`card_set_id` AS `card_set_id`,`c`.`card_type` AS `card_type`,`c`.`card_type_id` AS `card_type_id`,`c`.`rarity` AS `rarity`,`c`.`rarity_id` AS `rarity_id`,`c`.`class_slug` AS `class_slug`,`c`.`class_id` AS `class_id`,`c`.`multi_class_json` AS `multi_class_json`,`c`.`minion_type` AS `minion_type`,`c`.`minion_type_id` AS `minion_type_id`,`c`.`spell_school` AS `spell_school`,`c`.`spell_school_id` AS `spell_school_id`,`c`.`mana_cost` AS `mana_cost`,`c`.`attack` AS `attack`,`c`.`health` AS `health`,`c`.`durability` AS `durability`,`c`.`armor` AS `armor`,`c`.`artist` AS `artist`,`c`.`image_url` AS `image_url`,`c`.`image_gold_url` AS `image_gold_url`,`c`.`image_signature_url` AS `image_signature_url`,`c`.`image_diamond_url` AS `image_diamond_url`,`c`.`animated_gold_url` AS `animated_gold_url`,`c`.`animated_signature_url` AS `animated_signature_url`,`c`.`animated_diamond_url` AS `animated_diamond_url`,`c`.`crop_image_url` AS `crop_image_url`,`c`.`local_image_url` AS `local_image_url`,`c`.`local_gold_image_url` AS `local_gold_image_url`,`c`.`local_crop_image_url` AS `local_crop_image_url`,`c`.`wiki_full_art_title` AS `wiki_full_art_title`,`c`.`wiki_full_art_url` AS `wiki_full_art_url`,`c`.`local_wiki_full_art_url` AS `local_wiki_full_art_url`,`c`.`wiki_full_art_file_page_url` AS `wiki_full_art_file_page_url`,`c`.`wiki_full_art_width` AS `wiki_full_art_width`,`c`.`wiki_full_art_height` AS `wiki_full_art_height`,`c`.`wiki_full_art_size` AS `wiki_full_art_size`,`c`.`wiki_full_art_sha1` AS `wiki_full_art_sha1`,`c`.`wiki_full_art_mime` AS `wiki_full_art_mime`,`c`.`wiki_full_art_fetched_at` AS `wiki_full_art_fetched_at`,`c`.`mechanics_json` AS `mechanics_json`,`c`.`referenced_tags_json` AS `referenced_tags_json`,`c`.`keyword_ids_json` AS `keyword_ids_json`,`c`.`wiki_page_title` AS `wiki_page_title`,`c`.`wiki_page_url` AS `wiki_page_url`,`c`.`source` AS `source`,`c`.`source_payload_json` AS `source_payload_json`,`c`.`source_hash` AS `source_hash`,`c`.`first_seen_at` AS `first_seen_at`,`c`.`last_seen_at` AS `last_seen_at`,`c`.`changed_at` AS `changed_at`,`c`.`created_at` AS `created_at`,`c`.`updated_at` AS `updated_at`,`f`.`in_format` AS `in_format`,`f`.`availability_status` AS `availability_status`,`f`.`rotation_year` AS `rotation_year`,`f`.`changed_at` AS `format_changed_at` from (`constructed_cards` `c` join `constructed_format_cards` `f` on(`f`.`card_id` = `c`.`card_id`)) where `f`.`format_slug` = 'standard';

-- ----------------------------------------------------------------------
CREATE ALGORITHM=UNDEFINED VIEW `constructed_wild_cards` AS select `c`.`card_id` AS `card_id`,`c`.`dbf` AS `dbf`,`c`.`slug` AS `slug`,`c`.`collectible` AS `collectible`,`c`.`name_ru` AS `name_ru`,`c`.`name_en` AS `name_en`,`c`.`text_ru` AS `text_ru`,`c`.`text_en` AS `text_en`,`c`.`flavor_ru` AS `flavor_ru`,`c`.`flavor_en` AS `flavor_en`,`c`.`card_set` AS `card_set`,`c`.`card_set_id` AS `card_set_id`,`c`.`card_type` AS `card_type`,`c`.`card_type_id` AS `card_type_id`,`c`.`rarity` AS `rarity`,`c`.`rarity_id` AS `rarity_id`,`c`.`class_slug` AS `class_slug`,`c`.`class_id` AS `class_id`,`c`.`multi_class_json` AS `multi_class_json`,`c`.`minion_type` AS `minion_type`,`c`.`minion_type_id` AS `minion_type_id`,`c`.`spell_school` AS `spell_school`,`c`.`spell_school_id` AS `spell_school_id`,`c`.`mana_cost` AS `mana_cost`,`c`.`attack` AS `attack`,`c`.`health` AS `health`,`c`.`durability` AS `durability`,`c`.`armor` AS `armor`,`c`.`artist` AS `artist`,`c`.`image_url` AS `image_url`,`c`.`image_gold_url` AS `image_gold_url`,`c`.`image_signature_url` AS `image_signature_url`,`c`.`image_diamond_url` AS `image_diamond_url`,`c`.`animated_gold_url` AS `animated_gold_url`,`c`.`animated_signature_url` AS `animated_signature_url`,`c`.`animated_diamond_url` AS `animated_diamond_url`,`c`.`crop_image_url` AS `crop_image_url`,`c`.`local_image_url` AS `local_image_url`,`c`.`local_gold_image_url` AS `local_gold_image_url`,`c`.`local_crop_image_url` AS `local_crop_image_url`,`c`.`wiki_full_art_title` AS `wiki_full_art_title`,`c`.`wiki_full_art_url` AS `wiki_full_art_url`,`c`.`local_wiki_full_art_url` AS `local_wiki_full_art_url`,`c`.`wiki_full_art_file_page_url` AS `wiki_full_art_file_page_url`,`c`.`wiki_full_art_width` AS `wiki_full_art_width`,`c`.`wiki_full_art_height` AS `wiki_full_art_height`,`c`.`wiki_full_art_size` AS `wiki_full_art_size`,`c`.`wiki_full_art_sha1` AS `wiki_full_art_sha1`,`c`.`wiki_full_art_mime` AS `wiki_full_art_mime`,`c`.`wiki_full_art_fetched_at` AS `wiki_full_art_fetched_at`,`c`.`mechanics_json` AS `mechanics_json`,`c`.`referenced_tags_json` AS `referenced_tags_json`,`c`.`keyword_ids_json` AS `keyword_ids_json`,`c`.`wiki_page_title` AS `wiki_page_title`,`c`.`wiki_page_url` AS `wiki_page_url`,`c`.`source` AS `source`,`c`.`source_payload_json` AS `source_payload_json`,`c`.`source_hash` AS `source_hash`,`c`.`first_seen_at` AS `first_seen_at`,`c`.`last_seen_at` AS `last_seen_at`,`c`.`changed_at` AS `changed_at`,`c`.`created_at` AS `created_at`,`c`.`updated_at` AS `updated_at`,`f`.`in_format` AS `in_format`,`f`.`availability_status` AS `availability_status`,`f`.`rotation_year` AS `rotation_year`,`f`.`changed_at` AS `format_changed_at` from (`constructed_cards` `c` join `constructed_format_cards` `f` on(`f`.`card_id` = `c`.`card_id`)) where `f`.`format_slug` = 'wild';

-- ----------------------------------------------------------------------
CREATE TABLE `corecard` (
  `corecard_id` int(11) NOT NULL AUTO_INCREMENT,
  `card_id` varchar(100) DEFAULT NULL,
  `dbf` int(11) DEFAULT NULL,
  `updated_dt` datetime DEFAULT NULL,
  `updated_by` varchar(100) DEFAULT NULL,
  `created_dt` datetime DEFAULT NULL,
  `created_by` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`corecard_id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;

-- ----------------------------------------------------------------------
CREATE TABLE `hearthstone_coins` (
  `card_id` varchar(64) NOT NULL,
  `dbf` int(10) unsigned DEFAULT NULL,
  `release_date` date DEFAULT NULL,
  `coin_name_en` varchar(180) NOT NULL,
  `card_name_ru` varchar(180) DEFAULT NULL,
  `card_name_en` varchar(180) DEFAULT NULL,
  `text_ru` text DEFAULT NULL,
  `text_en` text DEFAULT NULL,
  `flavor_text` text DEFAULT NULL,
  `artist` varchar(255) DEFAULT NULL,
  `image_url` varchar(512) DEFAULT NULL,
  `image_gold_url` varchar(512) DEFAULT NULL,
  `crop_image_url` varchar(512) DEFAULT NULL,
  `wiki_image_url` varchar(512) DEFAULT NULL,
  `wiki_image_file` varchar(255) DEFAULT NULL,
  `wiki_page_title` varchar(255) DEFAULT NULL,
  `wiki_page_url` varchar(512) DEFAULT NULL,
  `cosmetic_sort_order` int(10) unsigned DEFAULT NULL,
  `generated_by_card_ids_json` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`generated_by_card_ids_json`)),
  `related_card_ids_json` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`related_card_ids_json`)),
  `generated_by_cards_json` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`generated_by_cards_json`)),
  `related_cards_json` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`related_cards_json`)),
  `source` varchar(64) NOT NULL,
  `source_payload_json` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`source_payload_json`)),
  `source_hash` char(64) DEFAULT NULL,
  `fetched_at` timestamp NULL DEFAULT NULL,
  `changed_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`card_id`),
  KEY `idx_coin_dbf` (`dbf`),
  KEY `idx_coin_sort` (`cosmetic_sort_order`),
  KEY `idx_coin_changed_at` (`changed_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ----------------------------------------------------------------------
CREATE TABLE `hearthstone_pets` (
  `variant_id` int(10) unsigned NOT NULL,
  `pet_id` int(10) unsigned NOT NULL,
  `pet_name` varchar(180) NOT NULL,
  `variant_name` varchar(180) NOT NULL,
  `level` smallint(5) unsigned DEFAULT NULL,
  `dbf` int(10) unsigned DEFAULT NULL,
  `release_date` date DEFAULT NULL,
  `card_id` varchar(64) DEFAULT NULL,
  `card_image_url` varchar(512) DEFAULT NULL,
  `end_screen_background_url` varchar(512) DEFAULT NULL,
  `gallery_json` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`gallery_json`)),
  `page_title` varchar(255) DEFAULT NULL,
  `page_url` varchar(512) DEFAULT NULL,
  `status` varchar(24) NOT NULL DEFAULT 'ok',
  `error` text DEFAULT NULL,
  `source` varchar(64) NOT NULL,
  `source_payload_json` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`source_payload_json`)),
  `source_hash` char(64) DEFAULT NULL,
  `fetched_at` timestamp NULL DEFAULT NULL,
  `changed_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`variant_id`),
  UNIQUE KEY `uniq_pet_card_id` (`card_id`),
  KEY `idx_pet_id` (`pet_id`),
  KEY `idx_pet_dbf` (`dbf`),
  KEY `idx_pet_level` (`pet_id`,`level`),
  KEY `idx_changed_at` (`changed_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ----------------------------------------------------------------------
CREATE TABLE `hero_skins` (
  `card_id` varchar(96) NOT NULL,
  `dbf` int(10) unsigned DEFAULT NULL,
  `release_date` date DEFAULT NULL,
  `page_title` varchar(255) NOT NULL,
  `page_url` varchar(512) NOT NULL,
  `name_en` varchar(255) NOT NULL,
  `class_id` smallint(5) unsigned DEFAULT NULL,
  `class_slug` varchar(64) DEFAULT NULL,
  `class_name_en` varchar(80) DEFAULT NULL,
  `class_name_ru` varchar(80) DEFAULT NULL,
  `health` smallint(6) DEFAULT NULL,
  `character_name` varchar(255) DEFAULT NULL,
  `actor` varchar(255) DEFAULT NULL,
  `artist` varchar(255) DEFAULT NULL,
  `rarity_slug` varchar(48) DEFAULT NULL,
  `rarity_name_en` varchar(80) DEFAULT NULL,
  `rarity_name_ru` varchar(80) DEFAULT NULL,
  `primary_category_slug` varchar(96) DEFAULT NULL,
  `primary_category_en` varchar(160) DEFAULT NULL,
  `primary_category_ru` varchar(160) DEFAULT NULL,
  `categories_json` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`categories_json`)),
  `tags_json` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`tags_json`)),
  `static_image_file` varchar(255) DEFAULT NULL,
  `static_image_url` varchar(512) DEFAULT NULL,
  `animated_image_file` varchar(255) DEFAULT NULL,
  `animated_image_url` varchar(512) DEFAULT NULL,
  `animated_asset_json` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`animated_asset_json`)),
  `full_art_file` varchar(255) DEFAULT NULL,
  `full_art_url` varchar(512) DEFAULT NULL,
  `gallery_json` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`gallery_json`)),
  `sounds_json` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`sounds_json`)),
  `source_payload_json` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`source_payload_json`)),
  `source_hash` char(64) DEFAULT NULL,
  `status` varchar(32) NOT NULL DEFAULT 'ok',
  `error` text DEFAULT NULL,
  `fetched_at` timestamp NULL DEFAULT NULL,
  `changed_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`card_id`),
  UNIQUE KEY `uniq_hero_skins_dbf` (`dbf`),
  KEY `idx_hero_skins_class` (`class_slug`),
  KEY `idx_hero_skins_category` (`primary_category_slug`),
  KEY `idx_hero_skins_status` (`status`),
  KEY `idx_hero_skins_changed_at` (`changed_at`),
  KEY `idx_hero_skins_rarity` (`rarity_slug`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ----------------------------------------------------------------------
CREATE TABLE `horizontal_art_assets` (
  `entity_type` varchar(32) NOT NULL,
  `entity_id` varchar(160) NOT NULL,
  `source_url` varchar(1024) NOT NULL,
  `source_kind` varchar(16) NOT NULL,
  `source_signature` char(64) NOT NULL,
  `local_image_url` varchar(512) DEFAULT NULL,
  `image_sha256` char(64) DEFAULT NULL,
  `recipe_version` varchar(64) NOT NULL,
  `status` varchar(16) NOT NULL DEFAULT 'ready',
  `last_error` text DEFAULT NULL,
  `generated_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`entity_type`,`entity_id`),
  KEY `idx_horizontal_art_status` (`status`),
  KEY `idx_horizontal_art_generated` (`generated_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ----------------------------------------------------------------------
CREATE TABLE `jobs` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `user_id` int(11) DEFAULT NULL,
  `language` varchar(255) NOT NULL DEFAULT '',
  `content` text NOT NULL,
  `hash` varchar(255) NOT NULL DEFAULT '',
  `output` varchar(255) NOT NULL DEFAULT '',
  `created` int(11) NOT NULL DEFAULT 0,
  `done` int(11) DEFAULT NULL,
  `class` varchar(255) NOT NULL DEFAULT '',
  `rating` int(11) NOT NULL DEFAULT 0,
  `dust` int(11) DEFAULT NULL,
  `is_arena` int(11) DEFAULT NULL,
  `string` text DEFAULT NULL,
  `title` text NOT NULL,
  `parent_id` int(11) NOT NULL DEFAULT 0,
  `rating_minus` int(11) NOT NULL DEFAULT 0,
  `guide` text DEFAULT NULL,
  `pic_title` varchar(255) DEFAULT NULL,
  `pic_back` varchar(255) DEFAULT NULL,
  `pic_class` int(11) DEFAULT NULL,
  `pic_water` varchar(255) DEFAULT NULL,
  `pic_logo` varchar(255) DEFAULT NULL,
  `pic_frame` varchar(255) DEFAULT NULL,
  `status` int(11) NOT NULL DEFAULT 0,
  `processing_at` int(11) DEFAULT NULL,
  `deck_type` int(11) NOT NULL DEFAULT 0,
  `in_row` int(11) DEFAULT NULL,
  `hide_dust` tinyint(1) DEFAULT NULL,
  `batch_key` varchar(64) DEFAULT NULL,
  `attempts` int(11) NOT NULL DEFAULT 0,
  `last_error` text DEFAULT NULL,
  `failed_at` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `j-to-u` (`user_id`),
  KEY `parent_id` (`parent_id`),
  KEY `class` (`class`),
  KEY `output` (`output`),
  KEY `idx-jobs-processing` (`status`,`done`,`processing_at`),
  KEY `idx-jobs-batch-key` (`batch_key`),
  KEY `idx-jobs-status-done-id` (`status`,`done`,`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;

-- ----------------------------------------------------------------------
CREATE TABLE `migration` (
  `version` varchar(180) NOT NULL,
  `apply_time` int(11) DEFAULT NULL,
  PRIMARY KEY (`version`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci;

-- ----------------------------------------------------------------------
CREATE TABLE `options` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `option_name` varchar(255) NOT NULL,
  `option_value` varchar(255) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx-options-option-name` (`option_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;

